### ISSUE TITLE
Suggested from https://github.com/alekseysolo

### ISSUE THREAD

**Issue by optimistex** [optimistex/yii2-expression#3]
Автор сообщения: @alekseysolo
Здравствуйте
Приношу извинения, что пишу сюда, просто раздела issue для fork нет.
Использую ваше решение в своих проектах, преимущественно логические выражения. Требуется условное присвоение значения переменным, например, a = 34 > 6 ? 23 : 32
На данный момент реализовал это с помощью внешней функции
```php
$eval->functions['if' ] = function($bool, $true, $false) {
		return $bool ? $true : $false;
	};
```

Если продолжаете работать над проектом, возможно это удастся встроить, к сожалению глубоко вникнуть в исходный код пока нет времени, а он довольно непрост для понимания.
Спасибо

**Comment by optimistex** [comment]
Здравствуйте Алексей!

В своем проекте столкнулся с той же задачей как и у вас. Решил почти так же.
Мой код из другого проекта:
```php
$e->functions = [
   // ..............
    'if' => function ($condition, $thenValue, $elseValue) {
        return $condition === true ? $thenValue : $elseValue;
    },
   // ..............
];
```
Не уверен, что будет удачной идеей встраивание тенарного оператора (?:) в math-expression.
Но можно встроить функцию if в компонент, что бы не влосипедить ее в остальных проектах.
Как вам такой вариант? 

Остается вопрос, какую версию функции встроить, вашу или мою!?

**Comment by alekseysolo** [comment]
Выражение не всегда может возвращать bool value, это может быть например число, с этой точки зрения мой вариант более гибок.

А само название возможно лучше взять из таблиц Гугла, там есть похожая функция, чтобы придерживаться какого либо стандарта. Впрочем это не существенно.
Спасибо за быстрый отклик.

**Comment by optimistex** [comment]
Готово!
