### ISSUE TITLE
Unreleased tags

### ISSUE THREAD

**Issue by pablo-sg-pacheco** [optimistex/yii2-expression#4]
Hi,

Thanks for the library.

I believe you need to release the tags. The last one I could get using Composer is 2.0.1.1 while it seems the real last tag is 2.2.0.

Would you please do that?

**Comment by optimistex** [comment]
@pablo-sg-pacheco It was available in TAGs https://github.com/optimistex/math-expression/tags

Ok, pushed them as releases: https://github.com/optimistex/math-expression/releases

Also, available releases you may see here: https://packagist.org/packages/optimistex/math-expression

**Comment by pablo-sg-pacheco** [comment]
Thanks
